### ISSUE TITLE
file_statistics.rb:115:in `block in is_code?': invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by mtkd** [relevance/rcov#31] opened 2009-10-04 15:05 UTC
Seen 2 other mentions of the same issue on isitruby19

/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/file_statistics.rb:115:in `block in is_code?': invalid byte sequence in US-ASCII (ArgumentError)

**Comment by ghost** [comment] 2009-10-04 15:15
Can you please provide some sample code?

**Comment by mtkd** [comment] 2009-10-04 16:01
Full trace:

/Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/file_statistics.rb:115:in `block in is_code?': invalid byte sequence in US-ASCII (ArgumentError)
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/file_statistics.rb:112:in`each'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/file_statistics.rb:112:in `each_with_index'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/file_statistics.rb:112:in`is_code?'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/file_statistics.rb:213:in `extend_heredocs'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/file_statistics.rb:40:in`initialize'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/base_formatter.rb:49:in `new'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/formatters/base_formatter.rb:49:in`add_file'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:143:in `block (2 levels) in dump_coverage_info'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:142:in`each'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:142:in `block in dump_coverage_info'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:135:in`each'
    from /Users/me/.rvm/gems/ruby/1.9.1/gems/relevance-rcov-0.9.2.1/lib/rcov/code_coverage_analyzer.rb:135:in `dump_coverage_info'
    from /Users/me/.rvm/ruby-1.9.1-p243/bin/rcov:428:in`block in <main>'

I tried it on a small Rails project and similar happened, it's first time I've used rcov so I don't know enough about what it is doing to isolate a recreatable piece of target code

**Comment by mtkd** [comment] 2009-10-04 16:49
Ah, I think it's because I'm using Shoulda, using the rake task below Rcov runs fine:

http://lojic.com/blog/2009/02/26/setup-shoulda-and-rcov-for-rails-222/

**Comment by ghost** [comment] 2009-10-12 12:29
ok thanks for the info

**Comment by stuart** [comment] 2009-10-26 04:42
I'm getting the same error. I'm not using Shoulda. I'll try to put together a failing example and narrow it down.

**Comment by stuart** [comment] 2009-10-26 04:56
I found a non ASCII character in one of my source files.
Perhaps rcov should catch the error here and print the offending filename, line number and line.

**Comment by abedra** [comment] 2009-10-26 12:18
Thanks for reporting this.  I will take a look at it this week and see what I can find.

**Comment by chastell** [comment] 2009-11-27 21:56
FWIW, I have plenty of non-US-ASCII characters in my source files and I’d much rather keep them – so finding a fix for this would be most appreciated. :)

You can reproduce by cloning [art-decomp](http://github.com/chastell/art-decomp) and trying to run ‘rake cov’ under Ruby 1.9 and RCov 0.9.6 – the RSpec specs will pass, but RCov will break with the ‘invalid byte sequence in US-ASCII’ error and won’t generate the coverage report.

**Comment by stuart** [comment] 2009-11-28 09:55
I noticed this bug was labeled Ruby 186, I'm only seeing it in 1.9.1

**Comment by benhutton** [comment] 2009-12-10 18:04
I'm getting this as well.  It's because, well, I have a file full of non ASCII characters.  I fixed this in the normal rails environments by adding the magic comment "# encoding: UTF-8" to the top of that file.  Rcov seems to not be respecting that.

**Comment by benhutton** [comment] 2009-12-10 19:59
Okay, so I hacked around it.  Add this right before the case statement that has the error in it (around line 113):

line.force_encoding("utf-8")

There's probably a better place to put this...

**Comment by badal** [comment] 2010-01-12 14:21
The problem is with the "tilde" character.

**Comment by vjt** [comment] 2010-03-21 15:19
Hi, I've stumbled upon the same problem and fixed with the following patch:

```
--- lib/rcov/code_coverage_analyzer.rb~ 2010-03-21 16:15:47.000000000 +0100
+++ lib/rcov/code_coverage_analyzer.rb  2010-03-21 16:11:49.000000000 +0100
@@ -250,6 +250,10 @@
     end

     def update_script_lines__
+      if '1.9'.respond_to?(:force_encoding)
+        SCRIPT_LINES__.each{|k,v| v.each{|src| src.try(:force_encoding, 'utf-8')}}
+      end
+
       @script_lines__ = @script_lines__.merge(SCRIPT_LINES__)
     end
```

Do you think it's a good place to put this in? :-)

**Comment by sgonyea** [comment] 2010-06-11 21:48
It certainly works for me

**Comment by prosm** [comment] 2010-06-29 15:20
We're getting the same error, any plans to add the path to the code?

**Comment by yrral86** [comment] 2010-08-03 21:03
I'm seeing the same after adding a test case that uses nokogiri (probably has some japanese somewhere in one of the files). line.force_encoding("utf-8") right before the case statement fixed it for me... would be great to see a proper fix incorporated.

**Comment by mackuba** [comment] 2010-08-07 14:51
I think that ideally rcov should detect the encoding line at the beginning of file ("# encoding: UTF-8") and set that encoding instead of assuming utf-8 (though that would work too in majority of the cases).

**Comment by paneq** [comment] 2010-12-09 14:07
I'm also experiencing this bug.

**Comment by paneq** [comment] 2010-12-09 14:43
Monkey patch that does not require changing source. To use unitl this bug is fixed:

<pre>
#Rakefile
MetricFu::Configuration.run do |config|
  config.rcov[:test_files] = ['lib/r.rb', ... ]
end

# lib/r.rb
Rcov::FileStatistics.class_eval do
  def initialize_with_encoding(_, lines, *params)
    lines.each{|l| l.force_encoding("BINARY")}
    initialize_without_encoding(_, lines, *params)
  end
  alias_method(:initialize_without_encoding, :initialize)
  alias_method(:initialize, :initialize_with_encoding)
end
</pre>

**Closed as completed** 2012-01-19 04:00 UTC
