### ISSUE TITLE
Incorrect coverage reported

### ISSUE THREAD

**Issue by jonleighton** [relevance/rcov#27] opened 2009-09-07 14:37 UTC
With the following code, rcov reports that the last line in the method is not covered:

```
def bla
  [1, 2, 3].map do |i|
    i
  end.join(",")
end
```

This works correctly:

```
def bla
  result = [1, 2, 3].map do |i|
    i
  end
  result.join(",")
end
```

**Comment by ghost** [comment] 2009-09-11 00:47
There is most likely a bug with the file statistics formatter.  I will take a look at it.

**Comment by ddollar** [comment] 2009-09-14 06:10
I can confirm this exact same case. Snow Leopard, Ruby 1.8.7 (default)

**Comment by ddollar** [comment] 2009-09-14 07:30
Another case that seems to be interpreted incorrectly is

```
def foo
  @foo ||= begin
    "value"
  end
end
```

It misses the line

```
@foo ||= begin
```

**Comment by abedra** [comment] 2009-09-15 12:34
Unfortunately there are some bugs with 187-p72 (SL default) that make this bug possible.  I just tried reproducing with the latest (187-p174) and things seem to be fixed.  The RCov test suite also fails in p-72 and passes in p-174.  I suggest either installing the latest version of 1.8.6 or 1.8.7.

**Comment by ghost** [comment] 2009-09-27 18:50
Closing this issue because the bugs here exist in the version of ruby bundled with Snow Leopard, not with RCov

**Closed as completed** 2009-09-27 18:51 UTC

**Comment by rafaelrosafu** [comment] 2010-03-02 21:40
I'm having the same problem with "||= begin" running Ruby Enterprise Edition 1.8.7 p-248 on Ubuntu 9.10, it doesn't seem to be a OS X specific problem.

**Comment by ghost** [comment] 2010-03-02 21:57
Yes, that is correct.  The problem is actually in the part of rcov that figures out what is considered a "line of code".  There are actually quite a few bugs in that part of RCov.
