### ISSUE TITLE
Messy output

### ISSUE THREAD

**Issue by ghost** [relevance/rcov#7] opened 2009-05-08 13:34 UTC
Any idea what&rsquo;s causing this messy output?

http://70.85.173.194/Screenshot.png

My actual code doesn&rsquo;t have most of the line breaks you see in the screenshot.

Here&rsquo;s my rake task:

require &rsquo;rcov/rcovtask&rsquo;

namespace :test do

namespace :coverage do
  desc &rsquo;Delete aggregate coverage data.&rsquo;
  task( :clean ){ rm_f &rsquo;coverage.data&rsquo; }
end
desc &rsquo;Aggregate code coverage for unit, functional and integration tests&rsquo;
task :coverage => &rsquo;test:coverage:clean&rsquo;
%w[ unit functional ].each do |target|
  namespace :coverage do
    Rcov::RcovTask.new( target ) do |t|
      t.libs << &rsquo;test&rsquo;
      t.test_files = FileList[ "test/#{ target }/*_test.rb" ]
      t.output_dir = "public/coverage/#{  target }"
      t.verbose = true
      t.rcov_opts << "--sort coverage --exclude gem,oci8 --rails --aggregate coverage.data"
    end
  end
  task :coverage => "test:coverage:#{ target }"
end

end

spicycode-rcov-0.8.1.5.6 installs clean but fails when used:

```
rake test:coverage (in /rails/foo) rm -f coverage.data rm -r public/coverage/unit /usr/bin/ruby1.8 -Ilib:test -S rcov --text-report --sort coverage --exclude gem,oci8 --rails --aggregate coverage.data -o "public/coverage/unit" "test/unit/agroup_subject_test.rb""test/unit/ugroup_test.rb" "test/unit/user_ugroup_test.rb" "test/unit/ugroup_permission_test.rb" "test/unit/bookmark_test.rb" "test/unit/user_preference_test.rb" "test/unit/groupset_test.rb" "test/unit/population_study_test.rb" "test/unit/subject_test.rb" "test/unit/population_test.rb" "test/unit/group_subject_test.rb" "test/unit/disease_study_test.rb" "test/unit/disease_test.rb" "test/unit/group_test.rb" "test/unit/people_address_test.rb" "test/unit/site_test.rb" "test/unit/address_test.rb" "test/unit/study_subject_test.rb" "test/unit/person_test.rb" "test/unit/permission_test.rb" "test/unit/study_test.rb" "test/unit/user_test.rb" "test/unit/preference_test.rb" "test/unit/analysis_group_test.rb" /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.1.5.6/bin/rcov:19:in require&rsquo;: no such file to load -- rcov/version (LoadError)

    from /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.1.5.6/bin/rcov:19

rake aborted! Command failed with status (1): [/usr/bin/ruby1.8 -Ilib:test -S rcov --text...]
```

(See full trace by running task with --trace)

[original LH ticket](http://relevance.lighthouseapp.com/projects/16869/tickets/9)

 This ticket has 0 attachment(s).

**Comment by spicycode** [comment] 2009-05-17 14:47
Duplicate of 6

**Closed as completed by spicycode** 2009-05-17 14:47 UTC
