### ISSUE TITLE
Rcov defines a private method "message" on Object

### ISSUE THREAD

**Issue by timrosenblatt** [relevance/rcov#28] opened 2009-09-15 14:07 UTC
We have an ActiveRecord object with a column "message" on it. When we call "message" from a controller or view, it gives us an error that it's trying to call a private method. We found that by removing relevance-rcov from the project, the error would go away. After some more debugging, it looked like the private message method was being defined on Object. Is it possible to change that method definition to a less-common name?

tim -at- timrosenblatt -dot- com for followup questions.

**Comment by ghost** [comment] 2009-09-18 12:23
Yes, I will take a look at this.  Can you provide a sample for me to test against?

**Comment by timrosenblatt** [comment] 2009-09-24 14:19
Definitely. If you want some more formal test code, lmk.

I can find this by going into my script/console in test mode (I require relevance-rcov for my test environment)

  RAILS_ENV=test script/console

And I run 

  Object.message

And I get a private method error. When I remove relevance-rcov from my /config/environments/test.rb file and remove the gem (to be sure), and then I go back into script/console in test mode, and run Object.message, I get a 

  NoMethodError: undefined method `message' for Object:Class

This is relevance-rcov 0.9

**Comment by timrosenblatt** [comment] 2009-09-24 14:21
Also, thanks. <3

**Comment by jerrett** [comment] 2009-09-24 18:18
I just ran into this as well :)

**Comment by ghost** [comment] 2009-09-27 18:41
I started down the troubleshooting path here and am not running into this problem.  If you look through the rcov source code for "message", you get http://gist.github.com/194923.  None of which define anything called message on Object.  I also require relevance-rcov in my rails projects in test.rb.  I tried running script/console in test mode and don't even see message defined on object (http://gist.github.com/194926).  This is with relevance-rcov 0.9.3.

**Comment by timrosenblatt** [comment] 2009-09-30 11:40
I just installed a fresh copy of the gem.

sudo gem install relevance-rcov
Password:
Building native extensions.  This could take a while...
Successfully installed relevance-rcov-0.9.2.1
1 gem installed

Then I went into irb and did the following.

irb(main):001:0> require 'rubygems'
=> true
irb(main):002:0> Object.message
NoMethodError: undefined method `message' for Object:Class
    from (irb):2
irb(main):003:0> require 'rcov'
=> true
irb(main):004:0> Object.message
NoMethodError: private method`message' called for Object:Class
    from (irb):4
irb(main):005:0> 

How could this be happening? Did this get fixed from 0.9.2.1 to 0.9.3?

**Comment by jerrett** [comment] 2009-10-01 23:26
Appears 0.9.3 is not available as a gem yet, is this an error or is it just not finished yet?

**Comment by ghost** [comment] 2009-10-02 12:31
0.9.3 is not available because it seems as though github is not building gems after the migration to Rackspace.  I was able to reproduce the issue here, but it seems as though something is incidentally doing this, because message isn't actually defined anywhere inside of RCov

**Comment by timrosenblatt** [comment] 2009-10-02 12:36
Could it be something that's getting included? Defining a method on Object named "message" is a real problem, since it's such a common attribute name. Could it be something that RCov is including, instead of RCov's code itself?

**Comment by ghost** [comment] 2009-10-02 12:45
I found it...

opensource/rcov/master > irb
require 'rubygems'
=> true

require 'inspector'
=> true

require 'rcov'
=> true

Object.send(:public, :message)
=> Object

Inspector.where_is_this_defined {Object.message}
=> "Object received message 'message', Line #537 of /Users/abedra/.ruby_versions/ruby_186/lib/ruby/1.8/mkmf.rb"

This is an issue from a while ago where mkmf is being used in the base formatter to gather files to exclude.  This needs to be refactored out into just a simple regexp.

**Comment by jerrett** [comment] 2009-10-02 16:55
Glad it's been found! .. where does one find this 'Inspector'? It looks very handy!

**Comment by timrosenblatt** [comment] 2009-10-04 03:03
http://github.com/spicycode/the-inspector Very cool stuff.

**Comment by ghost** [comment] 2009-10-12 12:29
sorry about the delay on this, it will get fixed up this week

**Comment by timrosenblatt** [comment] 2009-10-13 12:27
No worries. I appreciate your efforts.

**Comment by abedra** [comment] 2009-10-16 13:38
This issue has been resolved in v0.9.4.  Please note that rcov is now using gemcutter to release gems.  Once you move to gemcutter you can just run gem install rcov (without the relevance part).

**Closed as completed by abedra** 2009-10-16 13:38 UTC

**Comment by timrosenblatt** [comment] 2009-10-19 12:26
You rock!
